/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/myRoom.glb -K -k 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/myRoom.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[-0.331, 0.843, -0.782]} rotation={[-3.01, 0.7, 2.985]} scale={0.368}>
          <group name="Armature" position={[-0.081, -1.599, -2.024]} rotation={[-3.083, 0.965, -3.123]} scale={2.147}>
            <primitive object={nodes.Hips} />
            <skinnedMesh name="Wolf3D_Body001" geometry={nodes.Wolf3D_Body001.geometry} material={materials['Wolf3D_Body.005']} skeleton={nodes.Wolf3D_Body001.skeleton} />
            <skinnedMesh name="Wolf3D_Hair001" geometry={nodes.Wolf3D_Hair001.geometry} material={materials['Wolf3D_Hair.005']} skeleton={nodes.Wolf3D_Hair001.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Bottom001" geometry={nodes.Wolf3D_Outfit_Bottom001.geometry} material={materials['Wolf3D_Outfit_Bottom.005']} skeleton={nodes.Wolf3D_Outfit_Bottom001.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Footwear001" geometry={nodes.Wolf3D_Outfit_Footwear001.geometry} material={materials['Wolf3D_Outfit_Footwear.005']} skeleton={nodes.Wolf3D_Outfit_Footwear001.skeleton} />
            <skinnedMesh name="Wolf3D_Outfit_Top001" geometry={nodes.Wolf3D_Outfit_Top001.geometry} material={materials['Wolf3D_Outfit_Top.005']} skeleton={nodes.Wolf3D_Outfit_Top001.skeleton} />
            <skinnedMesh name="EyeLeft001" geometry={nodes.EyeLeft001.geometry} material={materials['Wolf3D_Eye.005']} skeleton={nodes.EyeLeft001.skeleton} morphTargetDictionary={nodes.EyeLeft001.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft001.morphTargetInfluences} />
            <skinnedMesh name="EyeRight001" geometry={nodes.EyeRight001.geometry} material={materials['Wolf3D_Eye.005']} skeleton={nodes.EyeRight001.skeleton} morphTargetDictionary={nodes.EyeRight001.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight001.morphTargetInfluences} />
            <skinnedMesh name="Wolf3D_Head001" geometry={nodes.Wolf3D_Head001.geometry} material={materials['Wolf3D_Skin.005']} skeleton={nodes.Wolf3D_Head001.skeleton} morphTargetDictionary={nodes.Wolf3D_Head001.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head001.morphTargetInfluences} />
            <skinnedMesh name="Wolf3D_Teeth001" geometry={nodes.Wolf3D_Teeth001.geometry} material={materials['Wolf3D_Teeth.005']} skeleton={nodes.Wolf3D_Teeth001.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth001.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth001.morphTargetInfluences} />
          </group>
        </group>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="b3348a24479c4d9e8a10405af84c5989fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode">
              <group name="_METRESS" position={[33.755, 55.238, -181.499]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="BIG_SHELF" position={[-154.533, 77.155, 100.384]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="BIG_SHELF_big_shelf_0" geometry={nodes.BIG_SHELF_big_shelf_0.geometry} material={materials.big_shelf} position={[0, 0, 0.05]} />
              </group>
              <group name="BIG_SHELF001" position={[-154.533, 57.29, -88.483]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="BIG_SHELF002" position={[-139.427, 67.13, -116.917]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="books__bottom" position={[-147.958, 50.064, 99.626]} rotation={[-Math.PI / 2, 0, 0]} scale={[75.501, 100, 100]}>
                <mesh name="books__bottom_books_0" geometry={nodes.books__bottom_books_0.geometry} material={materials.books} position={[0, 0, 0.053]} />
              </group>
              <group name="books_middle_2" position={[-149.217, 82.224, 81.164]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="books_middle_2_books_0" geometry={nodes.books_middle_2_books_0.geometry} material={materials.books} position={[0, 0, 0.045]} />
              </group>
              <group name="books_middle_more" position={[-148.222, 82.682, 110.282]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="books_middle_more_books_0" geometry={nodes.books_middle_more_books_0.geometry} material={materials.books} position={[0, 0, 0.036]} />
              </group>
              <group name="books_top_3" position={[-148.408, 109.571, 113.931]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="books_top_3_books_0" geometry={nodes.books_top_3_books_0.geometry} material={materials.books} position={[0, 0, 0.049]} />
              </group>
              <group name="books_top_more" position={[-148.924, 115.377, 90.704]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="books_top_more_books_0" geometry={nodes.books_top_more_books_0.geometry} material={materials.books} position={[0, 0, 0.058]} />
              </group>
              <group name="books001" position={[-112.04, 101.7, -239.607]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="books002" position={[-149.78, 90.723, 47.716]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="books002_books_on_desk_0" geometry={nodes.books002_books_on_desk_0.geometry} material={materials.books_on_desk} position={[0, 0.301, -0.066]} />
              </group>
              <group name="BOTTOM_SHELFS" position={[-18.575, 24.122, -143.458]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="BOTTOM_SHELFS001" position={[-108.09, 61.781, -177.59]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="BOTTOM_SHELFS002" position={[-108.09, 61.781, -230.375]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <group name="box_shelf_lid001" position={[-0.009, 0.001, 0.123]} />
              </group>
              <group name="box" position={[-148.83, 139.171, 108.212]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <group name="top_box" position={[-0.288, 0.041, 0.073]} />
              </group>
              <group name="carpet_2" position={[131.994, 15.111, -48.952]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="chair" position={[-69.865, 69.418, 6.313]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="chair_chair_0" geometry={nodes.chair_chair_0.geometry} material={materials.chair} position={[-0.009, 0.301, -0.033]} scale={0.958} />
              </group>
              <group name="CLOCK" position={[-95.616, 101.084, -198.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="coffee_table" position={[105.786, 38.647, 34.171]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="coffee_table_coffee_table_0" geometry={nodes.coffee_table_coffee_table_0.geometry} material={materials.coffee_table} position={[0.264, 0.455, -0.013]} rotation={[0, 0, 2.018]} />
              </group>
              <group name="COUCH" position={[159.858, 38.1, 78.787]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="COUCH_couch_0" geometry={nodes.COUCH_couch_0.geometry} material={materials.couch} position={[-0.263, 1.752, 0]} rotation={[0, 0, 1.589]} />
              </group>
              <group name="FLOOR_BOARDS" position={[19.739, 8.28, 132.679]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="FLOOR_BOARDS_floor_0" geometry={nodes.FLOOR_BOARDS_floor_0.geometry} material={materials.floor} position={[0, 0, 0.039]} />
              </group>
              <group name="flower" position={[110.038, 81.02, -168.687]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="flower001" position={[143.838, 58.76, 84.039]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="flower001_CHAIR_CUSION_0" geometry={nodes.flower001_CHAIR_CUSION_0.geometry} material={materials.CHAIR_CUSION} position={[-0.047, 1.645, 0]} rotation={[0, 0, 1.589]} />
              </group>
              <group name="LAPTOP002" position={[-121.011, 84.727, 5.467]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="LAPTOP002_kayboard_0" geometry={nodes.LAPTOP002_kayboard_0.geometry} material={materials.kayboard} position={[-0.021, 0.235, -0.05]} scale={[0.855, 1.163, 1.096]} />
              </group>
              <group name="LAPTOP003" position={[-151.403, 110.55, 5.468]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="LAPTOP003_pc_0" geometry={nodes.LAPTOP003_pc_0.geometry} material={materials.material_15} position={[0, 0.301, -0.009]} scale={1.178} />
                <mesh name="LAPTOP003_screen_0" geometry={nodes.LAPTOP003_screen_0.geometry} material={materials.screen} position={[0, 0.301, -0.009]} scale={1.178} />
              </group>
              <group name="MOUSE" position={[-117.748, 84.431, -23.727]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="MOUSE_mouse_0" geometry={nodes.MOUSE_mouse_0.geometry} material={materials.mouse} position={[-0.022, 0.253, -0.056]} scale={1.076} />
              </group>
              <group name="MUG" position={[-133.191, 90.4, -35.434]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="MUG_cup_of_coffee_0" geometry={nodes.MUG_cup_of_coffee_0.geometry} material={materials.cup_of_coffee} position={[0, 0.301, -0.083]} />
              </group>
              <group name="MUG001" position={[102.945, 66.273, 58.08]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="MUG001_cup_of_coffee_0" geometry={nodes.MUG001_cup_of_coffee_0.geometry} material={materials.cup_of_coffee} position={[0.521, 0.771, 0]} rotation={[0, 0, 2.018]} />
              </group>
              <group name="PENCIL_CUP" position={[-145.6, 100.887, 46.529]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="PENCIL_CUP_pencil_holder_0" geometry={nodes.PENCIL_CUP_pencil_holder_0.geometry} material={materials.pencil_holder} position={[0, 0.301, -0.066]} />
              </group>
              <group name="pencils002" position={[-146.82, 105.956, 49.363]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="pencils002_pencils_0" geometry={nodes.pencils002_pencils_0.geometry} material={materials.pencils} position={[0, 0.301, -0.066]} />
              </group>
              <group name="picture_frames" position={[-168.687, 162.077, -3.303]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="picture_frames_pictures_0" geometry={nodes.picture_frames_pictures_0.geometry} material={materials.pictures} position={[1.374, 1.228, 0]} rotation={[0, 0, -1.563]} />
              </group>
              <group name="picture_frames006" position={[-168.687, 109.259, 36.913]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="PILLOW" position={[-46.345, 64.218, -211.287]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="pillow_cat001" position={[35.349, 90.763, -219.473]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="PILLOWS_COUCH" position={[151.193, 42, 31.345]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="PILLOWS_COUCH_cussion_on_couch_0" geometry={nodes.PILLOWS_COUCH_cussion_on_couch_0.geometry} material={materials.cussion_on_couch} position={[-0.649, 1.182, 0]} rotation={[0, 0, 1.589]} />
              </group>
              <group name="PLANTS_DESK002" position={[-142.7, 143.83, 87.032]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="PLANTS_DESK002_plant_on_desk_0" geometry={nodes.PLANTS_DESK002_plant_on_desk_0.geometry} material={materials.plant_on_desk} position={[0.004, -0.147, 0.046]} />
              </group>
              <group name="sheet" position={[44.384, 64.991, -179.926]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="SHELFS" position={[-118.334, 52.097, -207.317]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="stars" position={[-52.552, 127.703, -262.188]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <group name="TABLE" position={[-134.633, 73.317, -1.265]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <group name="TABLE001" position={[1.035, -0.394, -0.127]} />
              </group>
              <group name="wardrob_door" position={[204.764, 96.379, -118.339]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model001">
          <group name="e8c856045463406eba283fd298911dbdfbx">
            <group name="RootNode001">
              <group name="bookmark001">
                <mesh name="bookmark001_empastado_1_0" geometry={nodes.bookmark001_empastado_1_0.geometry} material={materials['empastado_1.001']} />
              </group>
              <group name="empastado_1001">
                <mesh name="empastado_1001_empastado_1_a_0" geometry={nodes.empastado_1001_empastado_1_a_0.geometry} material={materials['empastado_1_a.001']} />
                <mesh name="empastado_1001_empastado_1_0" geometry={nodes.empastado_1001_empastado_1_0.geometry} material={materials['empastado_1.001']} />
              </group>
              <group name="empastado_2001">
                <mesh name="empastado_2001_empastado_0" geometry={nodes.empastado_2001_empastado_0.geometry} material={materials['empastado.001']} />
              </group>
              <group name="golden_frame_1001">
                <mesh name="golden_frame_1001_gold_paint_0" geometry={nodes.golden_frame_1001_gold_paint_0.geometry} material={materials['gold_paint.001']} />
                <mesh name="golden_frame_1001_gold_paint_0001" geometry={nodes.golden_frame_1001_gold_paint_0001.geometry} material={materials['gold_paint.001']} />
              </group>
              <group name="golden_pages">
                <mesh name="golden_pages_gold_paint_0" geometry={nodes.golden_pages_gold_paint_0.geometry} material={materials['gold_paint.001']} />
              </group>
              <group name="hard_cover001">
                <mesh name="hard_cover001_Black_Leather_0" geometry={nodes.hard_cover001_Black_Leather_0.geometry} material={materials['Black_Leather.001']} />
              </group>
              <group name="text_pages1">
                <mesh name="text_pages1_text_1_0" geometry={nodes.text_pages1_text_1_0.geometry} material={materials.text_1} />
              </group>
              <group name="text_pages2">
                <mesh name="text_pages2_text_2_0" geometry={nodes.text_pages2_text_2_0.geometry} material={materials.text_2} />
              </group>
            </group>
          </group>
        </group>
        <group name="RootNode002">
          <group name="Node003" position={[-1.338, 0.574, -0.265]} rotation={[-1.571, -0.007, 1.57]}>
            <mesh name="Node003_1" geometry={nodes.Node003_1.geometry} material={materials._5_Drawer} />
            <mesh name="Node003_2" geometry={nodes.Node003_2.geometry} material={materials._5_Drawer_1} />
          </group>
        </group>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.WALL} position={[0.184, -0.005, 0.137]} scale={[1.884, 1, 1.424]} />
        <group name="Standing_lamp_01_Circle003" position={[-1.523, 0.157, -1.123]}>
          <mesh name="Standing_lamp_01_Circle003-Mesh" geometry={nodes['Standing_lamp_01_Circle003-Mesh'].geometry} material={materials['795548']} />
          <mesh name="Standing_lamp_01_Circle003-Mesh_1" geometry={nodes['Standing_lamp_01_Circle003-Mesh_1'].geometry} material={materials.DD9944} />
          <mesh name="Standing_lamp_01_Circle003-Mesh_2" geometry={nodes['Standing_lamp_01_Circle003-Mesh_2'].geometry} material={materials['455A64']} />
          <mesh name="Standing_lamp_01_Circle003-Mesh_3" geometry={nodes['Standing_lamp_01_Circle003-Mesh_3'].geometry} material={materials.FFEB3B} />
        </group>
        <group name="guitar" position={[0.084, 0.161, -0.946]}>
          <mesh name="Mesh59_Model_1" geometry={nodes.Mesh59_Model_1.geometry} material={materials._LightGray_} />
          <mesh name="Mesh59_Model_1_1" geometry={nodes.Mesh59_Model_1_1.geometry} material={materials._Tan_} />
          <mesh name="Mesh59_Model_1_2" geometry={nodes.Mesh59_Model_1_2.geometry} material={materials._SaddleBrown_} />
          <mesh name="Mesh59_Model_1_3" geometry={nodes.Mesh59_Model_1_3.geometry} material={materials._Gold_} />
          <mesh name="Mesh59_Model_1_4" geometry={nodes.Mesh59_Model_1_4.geometry} material={materials.scan_4} />
          <mesh name="Mesh59_Model_1_5" geometry={nodes.Mesh59_Model_1_5.geometry} material={materials._Gray_} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/myRoom.glb')
