/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/myRoom.glb -k 
*/

import React, { useEffect, useRef } from "react";
import * as THREE from "three";
import { useGLTF, useTexture } from "@react-three/drei";
import { gsap } from "gsap";

export function MyRoom(props) {
  const { section } = props;
  const guitarRef = useRef();
  const chairRef = useRef();
  const mugRef = useRef();
  const coffeeTableRef = useRef();
  const { nodes, materials } = useGLTF("/models/myRoom.glb");
  const floorTexture = useTexture("/textures/floor.jpg");
  const woodTexture = useTexture("/textures/wood.jpg");
  const screenTexture = useTexture("/textures/screen.png");

  const chairMaterial = new THREE.MeshPhongMaterial({
    color: "#8D667F",
  });
  const floorMaterial = new THREE.MeshPhongMaterial({
    map: floorTexture,
    color: "#dfc5a9",
  });
  const woodMaterial = new THREE.MeshPhongMaterial({
    map: woodTexture,
    color: "#c4935b",
  });
  const screenMaterial = new THREE.MeshPhongMaterial({
    map: screenTexture,
  });

  useEffect(() => {
    if (guitarRef.current) {
      gsap.to(guitarRef.current.scale, {
        x: section === 0 ? 1 : 0,
        y: section === 0 ? 1 : 0,
        z: section === 0 ? 1 : 0,
        duration: 1,
        ease: "back.out(1.7)",
      });
    }
    if (chairRef.current) {
      gsap.to(chairRef.current.scale, {
        x: section === 0 ? 100 : 0,
        y: section === 0 ? 100 : 0,
        z: section === 0 ? 100 : 0,
        duration: 1,
        ease: "back.out(1.7)",
      });
    }
    if (coffeeTableRef.current) {
      gsap.to(coffeeTableRef.current.scale, {
        x: section === 0 ? 100 : 0,
        y: section === 0 ? 100 : 0,
        z: section === 0 ? 100 : 0,
        duration: 1,
        ease: "back.out(1.7)",
      });
    }
    if (mugRef.current) {
      gsap.to(mugRef.current.scale, {
        x: section === 0 ? 100 : 0,
        y: section === 0 ? 100 : 0,
        z: section === 0 ? 100 : 0,
        duration: 1,
        ease: "back.out(1.7)",
      });
    }
  }, [section]);
  return (
    <group {...props} dispose={null}>
      <pointLight
        name="Point001"
        intensity={5.229}
        decay={2}
        position={[-1.587, 1.259, -1.171]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        name="Point002"
        intensity={3.333}
        decay={2}
        position={[-1.501, 1.406, -1.157]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Plane"
        geometry={nodes.Plane.geometry}
        material={materials.WALL}
        position={[0.184, 0.087, 0.137]}
        scale={[1.884, 1, 1.424]}
      />
      <group
        name="Standing_lamp_01_Circle003"
        position={[-1.523, 0.157, -1.123]}
      >
        <mesh
          name="Standing_lamp_01_Circle003-Mesh"
          geometry={nodes["Standing_lamp_01_Circle003-Mesh"].geometry}
          material={materials["795548"]}
        />
        <mesh
          name="Standing_lamp_01_Circle003-Mesh_1"
          geometry={nodes["Standing_lamp_01_Circle003-Mesh_1"].geometry}
          material={materials.DD9944}
        />
        <mesh
          name="Standing_lamp_01_Circle003-Mesh_2"
          geometry={nodes["Standing_lamp_01_Circle003-Mesh_2"].geometry}
          material={materials["455A64"]}
        />
        <mesh
          name="Standing_lamp_01_Circle003-Mesh_3"
          geometry={nodes["Standing_lamp_01_Circle003-Mesh_3"].geometry}
          material={materials.FFEB3B}
        />
      </group>
      <group
        ref={guitarRef}
        name="guitar"
        position={[0.084, 0.161, -0.946]}
        scale={[0, 0, 0]}
      >
        <mesh
          name="Mesh59_Model_1"
          geometry={nodes.Mesh59_Model_1.geometry}
          material={materials._LightGray_}
        />
        <mesh
          name="Mesh59_Model_1_1"
          geometry={nodes.Mesh59_Model_1_1.geometry}
          material={materials._Tan_}
        />
        <mesh
          name="Mesh59_Model_1_2"
          geometry={nodes.Mesh59_Model_1_2.geometry}
          material={materials._SaddleBrown_}
        />
        <mesh
          name="Mesh59_Model_1_3"
          geometry={nodes.Mesh59_Model_1_3.geometry}
          material={materials._Gold_}
        />
        <mesh
          name="Mesh59_Model_1_4"
          geometry={nodes.Mesh59_Model_1_4.geometry}
          material={materials.scan_4}
        />
        <mesh
          name="Mesh59_Model_1_5"
          geometry={nodes.Mesh59_Model_1_5.geometry}
          material={materials._Gray_}
        />
      </group>
      <group name="b3348a24479c4d9e8a10405af84c5989fbx" scale={0.01}>
        <group
          name="books002"
          position={[-149.78, 90.723, 47.716]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            name="books002_books_on_desk_0"
            geometry={nodes.books002_books_on_desk_0.geometry}
            material={materials.books_on_desk}
            position={[0, 0.301, 0]}
          />
        </group>
        <mesh
          name="box_BOX_ON_SHELF_0"
          geometry={nodes.box_BOX_ON_SHELF_0.geometry}
          material={materials.BOX_ON_SHELF}
          position={[-148.83, 139.171, 108.212]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <group
          ref={chairRef}
          name="chair"
          position={[-69.865, 69.418, 6.313]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0, 0, 0]}
        >
          <mesh
            name="chair_chair_0"
            geometry={nodes.chair_chair_0.geometry}
            material={chairMaterial}
            position={[0, 0.301, 0]}
          />
        </group>
        <group
          ref={coffeeTableRef}
          name="coffee_table"
          position={[105.786, 38.647, 34.171]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0, 0, 0]}
        >
          <mesh
            name="coffee_table_coffee_table_0"
            geometry={nodes.coffee_table_coffee_table_0.geometry}
            material={woodMaterial}
            position={[0.264, 0.455, -0.013]}
            rotation={[0, 0, 2.018]}
          />
        </group>
        <group
          name="COUCH"
          position={[159.858, 38.1, 78.787]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            name="COUCH_couch_0"
            geometry={nodes.COUCH_couch_0.geometry}
            material={chairMaterial}
            position={[-0.263, 1.752, 0]}
            rotation={[0, 0, 1.589]}
          />
        </group>
        <group
          name="FLOOR_BOARDS"
          position={[19.739, 8.28, 132.679]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            name="FLOOR_BOARDS_floor_0"
            geometry={nodes.FLOOR_BOARDS_floor_0.geometry}
            material={floorMaterial}
            position={[0, 0, 0.039]}
          />
        </group>
        <group
          name="flower001"
          position={[143.838, 58.76, 84.039]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            name="flower001_CHAIR_CUSION_0"
            geometry={nodes.flower001_CHAIR_CUSION_0.geometry}
            material={materials.CHAIR_CUSION}
            position={[-0.047, 1.645, 0]}
            rotation={[0, 0, 1.589]}
          />
        </group>
        <group
          name="LAPTOP002"
          position={[-121.011, 84.727, 5.467]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            name="LAPTOP002_kayboard_0"
            geometry={nodes.LAPTOP002_kayboard_0.geometry}
            material={materials.kayboard}
            position={[0, 0.301, 0]}
          />
        </group>
        <group
          name="LAPTOP003"
          position={[-151.403, 110.55, 5.468]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            name="LAPTOP003_pc_0"
            geometry={nodes.LAPTOP003_pc_0.geometry}
            material={materials.material_15}
            position={[0, 0.301, 0]}
          />
          <mesh
            name="LAPTOP003_screen_0"
            geometry={nodes.LAPTOP003_screen_0.geometry}
            material={screenMaterial}
            position={[0, 0.301, 0]}
          />
        </group>
        <group
          name="MOUSE"
          position={[-117.748, 84.431, -23.727]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            name="MOUSE_mouse_0"
            geometry={nodes.MOUSE_mouse_0.geometry}
            material={materials.mouse}
            position={[0, 0.301, 0]}
          />
        </group>
        <group
          name="MUG"
          position={[-133.191, 90.4, -35.434]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            name="MUG_cup_of_coffee_0"
            geometry={nodes.MUG_cup_of_coffee_0.geometry}
            material={materials.cup_of_coffee}
            position={[0, 0.301, 0]}
          />
        </group>
        <group
          ref={mugRef}
          name="MUG001"
          position={[102.945, 66.273, 58.08]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0, 0, 0]}
        >
          <mesh
            name="MUG001_cup_of_coffee_0"
            geometry={nodes.MUG001_cup_of_coffee_0.geometry}
            material={materials.cup_of_coffee}
            position={[0.521, 0.771, 0]}
            rotation={[0, 0, 2.018]}
          />
        </group>
        <group
          name="PENCIL_CUP"
          position={[-145.6, 100.887, 46.529]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            name="PENCIL_CUP_pencil_holder_0"
            geometry={nodes.PENCIL_CUP_pencil_holder_0.geometry}
            material={materials.pencil_holder}
            position={[0, 0.301, 0]}
          />
        </group>
        <group
          name="pencils002"
          position={[-146.82, 105.956, 49.363]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            name="pencils002_pencils_0"
            geometry={nodes.pencils002_pencils_0.geometry}
            material={materials.pencils}
            position={[0, 0.301, 0]}
          />
        </group>
        <group
          name="picture_frames"
          position={[-168.687, 162.077, -3.303]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            name="picture_frames_pictures_0"
            geometry={nodes.picture_frames_pictures_0.geometry}
            material={materials.pictures}
            position={[1.374, 1.228, 0]}
            rotation={[0, 0, -1.563]}
          />
        </group>
        <group
          name="PILLOWS_COUCH"
          position={[151.193, 42, 31.345]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            name="PILLOWS_COUCH_cussion_on_couch_0"
            geometry={nodes.PILLOWS_COUCH_cussion_on_couch_0.geometry}
            material={materials.cussion_on_couch}
            position={[-0.649, 1.182, 0]}
            rotation={[0, 0, 1.589]}
          />
        </group>
        <group
          name="TABLE"
          position={[-134.633, 73.317, -1.265]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <group name="TABLE001" position={[1.035, -0.394, -0.127]}>
            <mesh
              name="TABLE001_desk_drawer_0"
              geometry={nodes.TABLE001_desk_drawer_0.geometry}
              material={materials.desk_drawer}
              position={[0, 0.301, 0]}
            />
          </group>
          <mesh
            name="TABLE_desk_0"
            geometry={nodes.TABLE_desk_0.geometry}
            material={materials.desk}
            position={[0, 0.301, 0]}
          />
        </group>
        <mesh
          name="BIG_SHELF_big_shelf_0"
          geometry={nodes.BIG_SHELF_big_shelf_0.geometry}
          material={woodMaterial}
          position={[-154.533, 77.155, 100.384]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          name="books__bottom_books_0"
          geometry={nodes.books__bottom_books_0.geometry}
          material={materials.books}
          position={[-147.958, 50.064, 99.626]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[75.501, 100, 100]}
        />
        <mesh
          name="books_middle_2_books_0"
          geometry={nodes.books_middle_2_books_0.geometry}
          material={materials.books}
          position={[-149.217, 82.224, 81.164]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          name="books_middle_more_books_0"
          geometry={nodes.books_middle_more_books_0.geometry}
          material={materials.books}
          position={[-148.222, 82.682, 110.282]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          name="books_top_3_books_0"
          geometry={nodes.books_top_3_books_0.geometry}
          material={materials.books}
          position={[-148.408, 109.571, 113.931]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          name="books_top_more_books_0"
          geometry={nodes.books_top_more_books_0.geometry}
          material={materials.books}
          position={[-148.924, 115.377, 90.704]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          name="PLANTS_DESK002_plant_on_desk_0"
          geometry={nodes.PLANTS_DESK002_plant_on_desk_0.geometry}
          material={materials.plant_on_desk}
          position={[-142.7, 143.83, 87.032]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
      <mesh
        name="bookmark001_empastado_1_0"
        geometry={nodes.bookmark001_empastado_1_0.geometry}
        material={materials["empastado_1.001"]}
      />
      <mesh
        name="empastado_1001_empastado_1_a_0"
        geometry={nodes.empastado_1001_empastado_1_a_0.geometry}
        material={materials["empastado_1_a.001"]}
      />
      <mesh
        name="empastado_1001_empastado_1_0"
        geometry={nodes.empastado_1001_empastado_1_0.geometry}
        material={materials["empastado_1.001"]}
      />
      <mesh
        name="empastado_2001_empastado_0"
        geometry={nodes.empastado_2001_empastado_0.geometry}
        material={materials["empastado.001"]}
      />
      <mesh
        name="golden_frame_1001_gold_paint_0"
        geometry={nodes.golden_frame_1001_gold_paint_0.geometry}
        material={materials["gold_paint.001"]}
      />
      <mesh
        name="golden_frame_1001_gold_paint_0001"
        geometry={nodes.golden_frame_1001_gold_paint_0001.geometry}
        material={materials["gold_paint.001"]}
      />
      <mesh
        name="golden_pages_gold_paint_0"
        geometry={nodes.golden_pages_gold_paint_0.geometry}
        material={materials["gold_paint.001"]}
      />
      <mesh
        name="hard_cover001_Black_Leather_0"
        geometry={nodes.hard_cover001_Black_Leather_0.geometry}
        material={materials["Black_Leather.001"]}
      />
      <mesh
        name="text_pages1_text_1_0"
        geometry={nodes.text_pages1_text_1_0.geometry}
        material={materials.text_1}
      />
      <mesh
        name="text_pages2_text_2_0"
        geometry={nodes.text_pages2_text_2_0.geometry}
        material={materials.text_2}
      />
    </group>
  );
}

useGLTF.preload("public/models/myRoom.glb");
